#helm install my-release oci://ghcr.io/nginxinc/charts/nginx-ingress --version 1.0.2


serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::739561048503:role/prod-expense-aws-load-balancer-controller-sa
