controller:
  service:
    internal:
      enabled: false
#    targetPorts:
#      http: http
#      https: http
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "external"
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"


## helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
## helm repo update
## helm install  ingress ingress-nginx/ingress-nginx -f ingress.yaml


